---
kind: pipeline
type: docker
name: daily-generation-routine

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone --recursive https://github.com/your-repo/your-project.git .

  - name: install-poetry
    image: python:3
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry --version
      - poetry install

  - name: run-updateCache
    image: python:3
    environment:
      LIMS_KEY:
        from_secret: LIMS_KEY
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - poetry run updateCache

  - name: run-generate
    image: python:3
    environment:
      ANTHROPIC_KEY:
        from_secret: ANTHROPIC_KEY
      LIMS_KEY:
        from_secret: LIMS_KEY
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - poetry run generate

  - name: commit-and-push
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git config --global user.name 'drone-ci[bot]'
      - git config --global user.email 'drone-ci[bot]@users.noreply.github.com'
      - git add .
      - git commit -m "automated daily generation routine"
      - git push https://oauth2:${GITHUB_TOKEN}@github.com/your-repo/your-project.git
