---
kind: pipeline
type: docker
name: daily-generation-routine

steps:
  - name: install-poetry
    image: mwalbeck/python-poetry:1-3.12
    environment:
      ANTHROPIC_KEY:
        from_secret: ANTHROPIC_KEY
      LIMS_KEY:
        from_secret: LIMS_KEY
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - poetry --version
      - poetry install
      - poetry run updateCache
      - poetry run generate

  - name: commit-and-push
    image: bitnami/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git config --global user.name $GIT_COMMITTER_NAME
      - git config --global user.email $GIT_AUTHOR_EMAIL
      - git add .
      - git commit -m "automated daily generation routine"
      - git remote set-url origin "https://$GITHUB_TOKEN@github.com/subdavis/open-journal-mpls.git"
      - git push --set-upstream origin main

trigger:
  event:
    - cron
  cron:
    - "daily-generation-routine"
 