---
kind: pipeline
type: docker
name: daily-generation-routine

steps:
  - name: install-poetry
    image: python:3
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="/root/.local/bin:$PATH"
      - poetry --version
      - poetry install
      - poetry run updateCache
      - poetry run generate

  - name: commit-and-push
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git config --global user.name 'drone-ci[bot]'
      - git config --global user.email 'drone-ci[bot]@users.noreply.github.com'
      - git add .
      - git commit -m "automated daily generation routine"
      - git push https://subdavis:${GITHUB_TOKEN}@github.com/subdavis/open-journal-mpls.git
