---
kind: pipeline
type: docker
name: daily-generation-routine

steps:
  - name: install-poetry
    image: mwalbeck/python-poetry:latest
    environment:
      ANTHROPIC_KEY:
        from_secret: ANTHROPIC_KEY
      LIMS_KEY:
        from_secret: LIMS_KEY
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - poetry --version
      - poetry install
      - poetry run updateCache
      - poetry run generate

  - name: commit-and-push
    image: bitnami/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git config --global user.name 'drone-ci[bot]'
      - git config --global user.email 'drone-ci[bot]@users.noreply.github.com'
      - git add .
      - git commit -m "automated daily generation routine"
      - git push "https://${GITHUB_TOKEN}@github.com/subdavis/open-journal-mpls.git"

trigger:
  event:
    - cron
  cron:
    - "daily-generation-routine"
 